---
title: "Contratos de Compras"
author: "Simoldes"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(readxl)

```

Fornecedores

```{r}

# Fornecedores
## Atenção! usar arquivo "Clientes e Fornecedores" !!!
# Old # fo_file <- here("data", "Fornecedores Simoldes 2025 junho.xlsx")
# Old # fo2_file <- here("data", "Clientes e Fornecedores 2025-07-09.xlsx")
fo_file <- here::here("data", "Fornecedore 2025-10-08.xlsx")
fo <- readxl::read_excel(path = fo_file) |> 
  janitor::clean_names() |> 
  select(#empresa,
         fo_id = lilinr,
         fo_matchcode = limatc,
         fo_name = liname,
         fo_name2 = likuna,
         fo_end1 = libran,
         fo_end2 = listra,
         fo_uf = krbdst,
         fo_cep = lipolz,
         fo_cidade = liwort,
         fo_cnpj = liidnr,
         fo_ie = kridbs,
         fo_country = liidld
         ) |> 
  mutate(fo_id = as.character(fo_id))


fo |> glimpse()

fo |> View()


```

Ler contratos

```{r}

# Contratos de Compra
cc_file <- here("data", "Contratos de Compra 2025-10-07.xlsx")

cc <- readxl::read_excel(path = cc_file) |> 
  janitor::clean_names() |> 
  rename(item = botenr,
         estabelecimento = bofirm,
         fo_id = bolinr,
         preco = bop001,
         moeda = bowacd,
         cc_id = bokonr,
         dt_inicio = boguvo,
         dt_termino = bogubi)

cc <- 
  cc |> 
  left_join(itens |> distinct(item, desc), join_by(item)) |> 
  left_join(fo |> select(fo_id, fo_matchcode, fo_name), join_by(fo_id)) |> 
  filter(!str_detect(fo_matchcode, "SIMOLDES")) |> 
  select(estabelecimento, item, desc, fo_id, fo_matchcode, fo_name, cc_id, dt_inicio, dt_termino, preco, moeda) |> 
  mutate(fo_matchcode = ifelse(is.na(fo_matchcode), fo_name, fo_matchcode)) |> 
  group_by(item, fo_id, cc_id) |> 
  summarise_all(list(first)) |> 
  select(fornecedor_id = fo_id, matchcode = fo_matchcode, forn_name = fo_name, estabelecimento, contrato_id = cc_id, item, desc, dt_inicio, dt_termino, preco, moeda)

cc |> nrow()
cc |> View()

cc |> write_csv("contratos.csv")

cc |> glimpse()

cc |> 
  group_by(fo_id, item, estabelecimento) |> 
  nest() |> View()
  mutate(tam = map(data, ~ . |> nrow() > 1)) |> 
  filter(tam == TRUE) |> 
  unnest() |> 
  select(-tam) |> 
  View()

# falta idenrificar as situações onde o mesmo item com o mesmo fornecedor para comparar os preços.
```

Ler itens

```{r}


p_importar <- read_rds("data/p-importar.rds")

mp <- 
  p_importar |> 
  select(item) |> 
  pull(item) |> 
  map(~ get_mp_from_bom(get_bom_from_id(., bom), itens)) |> 
  reduce(rbind)

mp <- 
  mp |> 
  group_by(item) |> 
  summarise(desc = first(desc),
            grupo_de_estoque = first(grupo_de_estoque),
            un = first(un),
            estabelecimento = first(estabelecimento),
            fam_com = first(fam_com),
            cod_comp = first(cod_comp))


```

## Itens cadastrados

```{r}

ja_cadastrados <- 
  readxl::read_excel(here::here("data", "2025-10-27-jah_cadastrados.xlsx"),
                     col_types = "text") |> 
  janitor::clean_names() |> 
  select(item)


ja_cadastrados <- 
  ja_cadastrados |> 
  filter(!str_detect(item, "^F")) |> 
  filter(!str_detect(item, "^I"))

itens_com_contratos <- 
  ja_cadastrados |> 
  left_join(cc, join_by(item))


fornecedores_para_cadastrar <- 
  itens_com_contratos |> 
  filter(!is.na(estabelecimento))  |> 
  left_join(fo, join_by(fo_id)) |> 
  distinct(fo_id)

fornecedores_para_cadastrar |> 
  left_join(fo, join_by(fo_id)) |> 
  mutate(fo_id = str_sub(fo_id, start = 5, end = -1)) |> 
  group_by(fo_id) |> 
  summarise_all(first) |> 
  write_csv2("fornecedores.csv")

```
