---
title: "Itens e Estruturas"
author: "Simoldes"
---

```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(here)
library(cellranger)
library(gdata)

```

## Itens

Carga de dados exportadas do XPert.

```{r}
#| warning: false

source("R/read-itens.R")
itens <- read_itens()

projetos <- read_rds("data/projetos.rds")

```

## Determinar a Carteira de Pedidos Simoldes

Para filtrar os itens que fazem parte da carteira de produtos simoldes atual vamos utilizar 2 fontes:

1.  Arquivos de Pedidos em Carteira
2.  Relatório de Vendas

#### Pedidos em Carteira

```{r}
source("R/carteira-pedidos.R")  

pedidos <- get_order_history()  

pedidos <-
  pedidos |>
  filter(
    !customer %in% c(
      "BELLS INDUSTRIA",
      "BIOPLASTICOS",
      "CEMAS DO BRASIL",
      "FAURECIA",
      "FAURECIA AUTOMOT. BRASIL",
      "FWC GANCHEIRAS",
      "HB - SMR LOCACAO DE",
      "HB SMR SP 0008-73",
      "INDUSERVICE SERVICOS",
      "KUNST",
      "LINKPLAS IND.PLASTIC",
      "MADIS CONFECCOES",
      "NEW TECH COMPANY",
      "NILKO TECNOLOGIA LTD",
      "OMEGA RECYCLING",
      "PKS PLASTICOS",
      "PLASMAPLAST",
      "SIMOLDES ACOS BRASIL",
      "SIMOLDES PLASTICOS",
      "SPI",
      "SUMMA POLIMEROS"
    )
  )


pedidos |> write_rds("data/carteira-pedidos.RDS")
pedidos <- read_rds("data/carteira-pedidos.RDS")

```

#### Relatórios de Vendas

```{r}

source("R/read-vendas.R")  

spb_vendas <- 
  get_itens_from_branch("SPB") 

spb_vendas <-
  spb_vendas |>
  mutate(filial = "SPB")

spi_vendas <- 
  get_itens_from_branch("SPI") 

spi_vendas <- 
  spi_vendas |> 
  mutate(filial = "SPI")  

vendas <- 
  rbind(spb_vendas, spi_vendas)

vendas <- 
  vendas |> 
  mutate(year = year(as.Date(status))) |> 
  group_by(item) |> 
  summarise(year = max(year))

# acrescentar informações de projeto
vendas <- 
  vendas |> 
  left_join(itens |> select(item, prj_sigla, prj_desc)) |>
  group_by(item, prj_sigla, prj_desc) |> 
  summarise(year = max(year, na.rm = TRUE)) |> 
  filter(str_detect(item, "^F"))

vendas |> write_rds("data/vendas.rds")
vendas <- read_rds("data/vendas.rds")

```

## Escopo - Importar

```{r}

# Vamos importar todos os produtos que aparecem nos relatórios de 
# Pedidos de Vendas 2025
p_importar <- 
  pedidos |>
  mutate(year = year(order_date)) |> 
  group_by(item) |> 
  summarise(year = max(year)) |> 
  left_join(itens |> select(item, prj_sigla, prj_desc)) |> 
  distinct(prj_sigla, prj_desc, year, item) |> 
  filter(str_detect(item, "^F"))

# Vamos acrescentar os produtos vendidos desde 2023
p_importar <-
  p_importar |> 
  rbind(vendas) |> 
  group_by(item) |> 
  summarise(prj_sigla = first(prj_sigla, na.rm = TRUE),
            prj_desc = first(prj_desc, na.rm = TRUE),
            year = max(year)) |> 
  select(item, prj_sigla, prj_desc, year) |> 
  filter(str_detect(item, "^F"))

p_importar |> write_rds("data/p-importar.rds")
p_importar <- read_rds("data/p-importar.rds")


```

### Alcance

Lista do que vai e não vai...

```{r}

##
# p_importar contém a lista de itens presentes nos Pedidos de Vendas e Relatórios de Vendas
p_importar

##
# cod_f contém todos os itens com código "F"
cod_f <- itens |> filter(str_detect(item, "^F")) |> select(item, prj_sigla, prj_desc)


## A lista de todos os itens que existem com o ano da última venda ou pedido é:
alcance <- cod_f |> left_join(p_importar)
alcance |> write_rds("data/alcance.rds")
alcance <- read_rds("data/alcance.rds")

```
