---
title: "Financeiro"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(here)


```

Fornecedores XPert

```{r}
file_fo <- here::here("data", "Fornecedore 2025-10-07.xlsx")

fo_ori <- 
  readxl::read_excel(file_fo) |> 
  janitor::clean_names()

fo <- 
  fo_ori |> 
  select(cod_fornec = lilinr, cnpj = liidnr) |> 
  distinct(cod_fornec, cnpj)

fo |> glimpse()

fo |> count(cod_fornec, cnpj, sort = TRUE)

```

Clientes

```{r}

file_cl <- here::here("data", "Clientes 2025-10-07.xlsx")

cl <- 
  readxl::read_excel(file_cl) |> 
  janitor::clean_names() |> 
  select(codigo = kdkdnr, 
         cnpj = kdidnr) |> 
  distinct(codigo, cnpj)

cl |> count(codigo, cnpj, sort = TRUE)

```

Informações de títulos do Luis Toledo

```{r}
file_tit <- here::here("data", "Base CR e CP - 092025.xlsx")

sheet_tit <- readxl::excel_sheets(file_tit)


```

SPB Contas a Pagar

```{r}
df_cp_spb <- 
  readxl::read_excel(file_tit,
                     sheet_tit[[1]]) |> 
  janitor::clean_names() |> 
  mutate(cod_fornec = as.character(cod_fornec)) |> 
  left_join(fo, join_by(cod_fornec)) |> 
  relocate(cnpj, .after = cod_fornec)
  
df_cp_spb |> View()
```

SPB Contas a Receber

```{r}
df_cr_spb <- 
  readxl::read_excel(file_tit,
                     sheet_tit[[2]],
                     skip = 1) |> 
  janitor::clean_names() |>
  mutate(codigo = as.character(codigo)) |> 
  left_join(cl, join_by(codigo)) |> 
  relocate(cnpj, .after = codigo)
  
df_cr_spb |> View()
```

SPI Contas a Receber

```{r}
df_cr_spi <-    
  readxl::read_excel(file_tit, sheet_tit[[4]], skip = 1) |>    
  janitor::clean_names() |>    
  mutate(codigo = as.character(codigo)) |>    
  left_join(fo, join_by(codigo == cod_fornec)) |>    
  relocate(cnpj, .after = codigo)    

df_cr_spi |> View()
```

SPI Contas a Pagar

```{r}
df_cp_spi <-    
  readxl::read_excel(file_tit,
                     sheet_tit[[2]],
                     skip = 1) |>    
  janitor::clean_names() |>   
  mutate(codigo = as.character(codigo)) |>    
  left_join(cl, join_by(codigo)) |>    
  relocate(cnpj, .after = codigo)    

df_cp_spi |> View()
```

Output

```{r}
df_cp_spb |> write_csv("cp_spb.csv")
df_cr_spb |> write_csv("cr_spb.csv")
df_cp_spi |> write_csv("cp_spi.csv")
df_cr_spi |> write_csv("cr_spi.csv")

```
