---
title: "Matéria Prima & Componentes"
format: html
editor: visual
---

```{r}
#| warning: false
#| echo: false

library(tidyverse)
library(stringr)
library(gt)
library(gtExtras)
library(scales)

```

Lista de Matérias Primas Utilizadas por Produto.

```{r}

cd0209_despesa_direta <- function(to_exp, out_file) {
  
  to_exp <- as.data.frame(dd_mat_escrt)
  out_file <- "teste.lst"

  # * = obrigatório
  cd0209_fix_width <- c(
    1,  # * trx: 1: create, 2: update, 3: delete
    16, # * id
    60, # * desc
    2,  # * grupo de estoque
    8,  # * família material
    8,  # família comercial
    2,  # * un
    5,  # * estabelecimento
    2,  # * situação: 1 ativo, 2 obsol ord auto, 3 obs todas, 4 totalmente obsoleto
    8,  # * data implantação
    8,  # * data liberação
    8,  # folha especificação
    2,  # * tipo controle: 1 físico, 2 total, 3 consignado, 4 débito direto
    2,  # * aplicação: 1 serviço, 2 material
    13, # lote econômico
    20, # código complementar
    16, # info complementares
    30, # imagem
    2000 # narrativa
  )

  #
  #
  # +----------------------------------------------------------------------------------------------------------------------------------+
  #   |                                             Layout do Arquivo de Importação de Itens                                             |
  #   |----------------------------------------------------------------------------------------------------------------------------------|
  #   |                                                     Nome do Arquivo: A ser informado                                             |
  #   |                                                             Formato: Texto                                                       |
  #   |                                                 Tamanho do Registro: 979                                                         |
  #   |----------------------------------------------------------------------------------------------------------------------------------|
  #   | Ordem |                         Descrição                       | Tamanho | Início | Término | Conteúdo | Decimais | Obrigatório |
  #   |-------+---------------------------------------------------------+---------+--------+---------+----------+----------+-------------|
  #   |    1  | Tipo de Transação                                       |     1   |     1  |     1   | Inteiro  |          |     Sim     |
  #   |       | Onde    1 - Inclusão                                    |         |        |         |          |          |             |
  #   |       |         2 - Modifição                                   |         |        |         |          |          |             |
  #   |       |         3 - Eliminação                                  |         |        |         |          |          |             |
  #   |    2  | Código do Item                                          |    16   |     2  |    17   | Caracter |          |     Sim     |
  #   |    3  | Descrição                                               |    60   |    18  |    77   | Caracter |          |     Sim     |
  #   |    4  | Código do Grupo de Estoque                              |     2   |    78  |    79   | Inteiro  |          |     Sim     |
  #   |    5  | Código da Família de Material                           |     8   |    80  |    87   | Caracter |          |     Sim     |
  #   |    6  | Família Comercial                                       |     8   |    88  |    95   | Caracter |          |     Não     |
  #   |    7  | Unidade de Medida                                       |     2   |    96  |    97   | Caracter |          |     Sim     |
  #   |    8  | Estabelecimento Padrão                                  |     5   |    98  |   102   | Caracter |          |     Sim     |
  #   |    9  | Situação                                                |     2   |   103  |   104   | Inteiro  |          |     Sim     |
  #   |       | Onde    1 - Ativo                                       |         |        |         |          |          |             |
  #   |       |         2 - Obsoleto Ordens Automáticas                 |         |        |         |          |          |             |
  #   |       |         3 - Obsoleto Todas as Ordens                    |         |        |         |          |          |             |
  #   |       |         4 - Totalmente Obsoleto                         |         |        |         |          |          |             |
  #   |   10  | Data de Implantação                                     |     8   |   105  |   112   | Data     |          |     Sim     |
  #   |       | Formato mmddaaaa                                        |         |        |         |          |          |             |
  #   |       | Onde    mm   = Mês                                      |         |        |         |          |          |             |
  #   |       |         dd   = Dia                                      |         |        |         |          |          |             |
  #   |       |         aaaa = Ano                                      |         |        |         |          |          |             |
  #   |   11  | Data de Liberação                                       |     8   |   113  |   120   | Data     |          |     Sim     |
  #   |       | Formato mmddaaaa                                        |         |        |         |          |          |             |
  #   |       | Onde    mm   = Mês                                      |         |        |         |          |          |             |
  #   |       |         dd   = Dia                                      |         |        |         |          |          |             |
  #   |       |         aaaa = Ano                                      |         |        |         |          |          |             |
  #   |   12  | Folha de Especificação                                  |     8   |   121  |   128   | Caracter |          |     Não     |
  #   |   13  | Tipo Controle                                           |     2   |   129  |   130   | Inteiro  |          |     Sim     |
  #   |       | Onde    1 - Físico                                      |         |        |         |          |          |             |
  #   |       |         2 - Total                                       |         |        |         |          |          |             |
  #   |       |         3 - Consignado                                  |         |        |         |          |          |             |
  #   |       |         4 - Débito Direto                               |         |        |         |          |          |             |
  #   |   14  | Aplicação (1-Serviço 2-Material)                        |     2   |   131  |   132   | Inteiro  |          |     Sim     |
  #   |       | Onde    1 - Serviço                                     |         |        |         |          |          |             |
  #   |       |         2 - Material                                    |         |        |         |          |          |             |
  #   |   15  | Lote Econômico                                          |    13   |   133  |   145   | Decimal  |     4    |     Não     |
  #   |   16  | Código Complementar                                     |    20   |   146  |   165   | Caracter |          |     Não     |
  #   |   17  | Informações Complementares                              |    16   |   166  |   181   | Caracter |          |     Não     |
  #   |   18  | Imagem                                                  |    30   |   182  |   211   | Caracter |          |     Não     |
  #   |   19  | Narrativa                                               |  2000   |   212  |  2211   | Caracter |          |     Não     |
  #   +----------------------------------------------------------------------------------------------------------------------------------+
  #
  #


  gdata::write.fwf(
    x = to_exp,
    file = out_file,
    width = cd0209_fix_width,
    colnames = FALSE,
    rownames = FALSE,
    sep = ""
  )
}

```

Importação de Matérias Primas e Componentes

```{r}
# Lista de F que vamos importar

dd_sheets <- excel_sheets(here("data", "MANUSIS ITENS_CATALOGADOS_MANUSIS.xlsx"))

dd_mat_escrt <- read_excel(
  here("data", "MANUSIS ITENS_CATALOGADOS_MANUSIS.xlsx"),
  sheet = dd_sheets[[1]]) |> 
  janitor::clean_names()

dd_mat_escrt <- 
  dd_mat_escrt |> 
  select(item = codigo_tag_do_material,
         desc = descricao_do_material) |> 
  mutate(fam_mat = "9940000") |> 
  mutate(un = "UN") |> 
  mutate(estabelecimento = "102",
         tipo_trx = 1,
         situacao = 1,
         dt_impl = "03032025",
        dt_lib = "03032025",
        folha = "",
        tipo_controle = 4,
        aplicacao =  1,
        lote_econ = 1,
        info = "",
        imagem = "",
        narrativa = "",
        fam_com = "",
        trx = 1,
        grupo_de_estoque = "99",
        cod_comp = "") 
  
dd_mat_escrt <- 
  dd_mat_escrt |> 
  mutate(desc = str_trunc(desc, 59, side = "right", ellipsis = "")) |> 
  mutate(desc = iconv(desc, from = "UTF-8", to = "ASCII//TRANSLIT")) |> 
  select(trx,
         item,
         desc,
         grupo_de_estoque,
         fam_mat,
         fam_com,
         un,
         estabelecimento,
         situacao,
         dt_impl,
         dt_lib,
         folha,
         tipo_controle,
         aplicacao,
         lote_econ,
         cod_comp,
         info,
         imagem,
         narrativa
         )
  
  
cd0209_despesa_direta(dd_mat_escrt, "mat_escr.lst")




```

## Materiais de Limpeza

```{r}

# Lista de F que vamos importar

dd_limpeza <- read_excel(
  here("data", "MANUSIS ITENS_CATALOGADOS_MANUSIS.xlsx"),
  sheet = dd_sheets[[2]]) |> 
  janitor::clean_names()

dd_limpeza <- 
  dd_limpeza |> 
  select(item = codigo_tag_do_material,
         desc = descricao_do_material) |> 
  mutate(fam_mat = "9920000") |> 
  mutate(un = "UN") |> 
  mutate(estabelecimento = "102",
         tipo_trx = 1,
         situacao = 1,
         dt_impl = "03032025",
        dt_lib = "03032025",
        folha = "",
        tipo_controle = 4,
        aplicacao =  1,
        lote_econ = 1,
        info = "",
        imagem = "",
        narrativa = "",
        fam_com = "",
        trx = 1,
        grupo_de_estoque = "99",
        cod_comp = "") 
  
dd_limpeza <- 
  dd_limpeza |> 
  mutate(desc = str_trunc(desc, 59, side = "right", ellipsis = "")) |> 
  mutate(desc = iconv(desc, from = "UTF-8", to = "ASCII//TRANSLIT")) |> 
  select(trx,
         item,
         desc,
         grupo_de_estoque,
         fam_mat,
         fam_com,
         un,
         estabelecimento,
         situacao,
         dt_impl,
         dt_lib,
         folha,
         tipo_controle,
         aplicacao,
         lote_econ,
         cod_comp,
         info,
         imagem,
         narrativa
         )
  
  
cd0209_despesa_direta(dd_limpeza, "limpeza.lst")

```

## EPI

```{r}


# Lista de F que vamos importar

dd_epi <- read_excel(
  here("data", "MANUSIS ITENS_CATALOGADOS_MANUSIS.xlsx"),
  sheet = dd_sheets[[3]]) |> 
  janitor::clean_names()

dd_epi <- 
  dd_epi |> 
  select(item = codigo_tag_do_material,
         desc = descricao_do_material) |> 
  mutate(fam_mat = "9910000") |> 
  mutate(un = "UN") |> 
  mutate(estabelecimento = "102",
         tipo_trx = 1,
         situacao = 1,
         dt_impl = "03032025",
        dt_lib = "03032025",
        folha = "",
        tipo_controle = 4,
        aplicacao =  1,
        lote_econ = 1,
        info = "",
        imagem = "",
        narrativa = "",
        fam_com = "",
        trx = 1,
        grupo_de_estoque = "99",
        cod_comp = "") 
  
dd_epi <- 
  dd_epi |> 
  mutate(desc = str_trunc(desc, 59, side = "right", ellipsis = "")) |> 
  mutate(desc = iconv(desc, from = "UTF-8", to = "ASCII//TRANSLIT")) |> 
  mutate(trx = 2) |> 
  select(trx,
         item,
         desc,
         grupo_de_estoque,
         fam_mat,
         fam_com,
         un,
         estabelecimento,
         situacao,
         dt_impl,
         dt_lib,
         folha,
         tipo_controle,
         aplicacao,
         lote_econ,
         cod_comp,
         info,
         imagem,
         narrativa
         )
  
  
cd0209_despesa_direta(dd_epi, "epi.lst")

```

## Manutenção

```{r}

# Lista de F que vamos importar

dd_manutencao <- read_excel(
  here("data", "MANUSIS ITENS_CATALOGADOS_MANUSIS.xlsx"),
  sheet = dd_sheets[[4]]) |> 
  janitor::clean_names()

dd_manutencao <- 
  dd_manutencao |> 
  select(item = codigo_tag_do_material,
         desc = descricao_do_material) |> 
  mutate(fam_mat = "9930000") |> 
  mutate(un = "UN") |> 
  mutate(estabelecimento = "102",
         tipo_trx = 1,
         situacao = 1,
         dt_impl = "03032025",
        dt_lib = "03032025",
        folha = "",
        tipo_controle = 4,
        aplicacao =  1,
        lote_econ = 1,
        info = "",
        imagem = "",
        narrativa = "",
        fam_com = "",
        trx = 1,
        grupo_de_estoque = "99",
        cod_comp = "") 
  
dd_manutencao <- 
  dd_manutencao |> 
  mutate(desc = str_trunc(desc, 59, side = "right", ellipsis = "")) |> 
  mutate(desc = iconv(desc, from = "UTF-8", to = "ASCII//TRANSLIT")) |> 
  mutate(item = iconv(item, from = "UTF-8", to = "ASCII//TRANSLIT")) |> 
  select(trx,
         item,
         desc,
         grupo_de_estoque,
         fam_mat,
         fam_com,
         un,
         estabelecimento,
         situacao,
         dt_impl,
         dt_lib,
         folha,
         tipo_controle,
         aplicacao,
         lote_econ,
         cod_comp,
         info,
         imagem,
         narrativa
         )
  
cd0209_despesa_direta(dd_manutencao, "manu.lst")

```
